apiVersion: v1
kind: Service
metadata:
  name: apigateway-service
spec:
  type: LoadBalancer
  loadBalancerIP: "34.101.129.145"
  selector:
    app: api-gateway
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
